### ISSUE TITLE
Formulario

### ISSUE THREAD

**Issue by yandivd** [yandivd/solicitud_dieta#2]
Carlos, si uso el form por default de django {{form}} todo pincha bien, pero cuando lo descompongo y le doy al boton no me crea la solicitud. La url es esta: http://localhost:8000/crear_solicitud/ 
Revisa y mira ver que pasa. El estilo del formulario es el que sale, es solo hacer que funcione

**Comment by yandivd** [comment]
Carlos mira a ver si puedes hacer el select del datefield para que salga el calendario y seleccionar la fecha

**Comment by carlosmca44** [comment]
El problema del formulario lo esta dando la condicion que pones de `action`
